#ifndef BBITEMINNERDATAKEY_H
#define BBITEMINNERDATAKEY_H
enum BbItemInnerDataKey {
    BBIIDK_ITEM_IS_SHAPE,
    BBIIDK_ITEM_IS_GROUP,
    BBIIDK_ITEM_ID,
    GRAPHICS_ITEM_DATA_KEY_DELETING
};
#endif // BBITEMINNERDATAKEY_H
