DEFINES += NSB_BLACKBOARD_DEV
#DEFINES += NSB_BLACKBOARD_PEN_ITEM_SMOOTHING
#DEFINES += NSB_BLACKBOARD_PEN_SAVE_TO_PIXMAP_WHEN_DONE
#DEFINES += NSB_BLACKBOARD_PEN_SMOOTHING_UNIT 15 # 开启线条圆滑后，圆滑曲线中每一小段直线的长度
#DEFINES += BLACKBOARD_ITEM_INDEX_SIGNAL
QT += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
include(blackboard.pri)
include(dev/dev.pri)
QMAKE_CXXFLAGS += -std=c++0x
win32
{
    QMAKE_LFLAGS_WINDOWS = /SUBSYSTEM:WINDOWS,5.01
    QMAKE_LFLAGS_CONSOLE = /SUBSYSTEM:CONSOLE,5.01

    DEFINES += _ATL_XP_TARGETING
    QMAKE_CFLAGS += /D _USING_V120_SDK71_
    QMAKE_CXXFLAGS += /D _USING_V120_SDK71_
}
