echo %dst%
xcopy /Y /I "%~dp0..\*.h" "%cd%\..\qt_blackboard_shared\include"
xcopy /Y /I /E "%cd%\release\*.dll" "%cd%\..\qt_blackboard_shared\bin\"
xcopy /Y /I /E "%cd%\release\*.lib" "%cd%\..\qt_blackboard_shared\lib\"
xcopy /Y /I /E "%cd%\release\*.pdb" "%cd%\..\qt_blackboard_shared\dev\"
xcopy /Y /I /E "%cd%\release\*.map" "%cd%\..\qt_blackboard_shared\dev\"
xcopy /Y /I /E "%cd%\debug\*.dll" "%cd%\..\qt_blackboard_shared\bin\"
xcopy /Y /I /E "%cd%\debug\*.lib" "%cd%\..\qt_blackboard_shared\lib\"
xcopy /Y /I /E "%cd%\debug\*.pdb" "%cd%\..\qt_blackboard_shared\dev\"
xcopy /Y /I /E "%cd%\debug\*.map" "%cd%\..\qt_blackboard_shared\dev\"
