#ifndef BBUTILSHEADER_H
#define BBUTILSHEADER_H

#ifdef NSB_BLACKBOARD_UTILS_DEV
#define NSB_BLACKBOARD_UTILS_EXPORT
#elif defined NSB_BLACKBOARD_UTILS_SHARED
#define NSB_BLACKBOARD_UTILS_EXPORT Q_DECL_EXPORT
#else
#define NSB_BLACKBOARD_UTILS_EXPORT Q_DECL_IMPORT
#endif

#endif // BBUTILSHEADER_H
