#ifndef BLACKBOARDHEADER_H
#define BLACKBOARDHEADER_H

#if defined(BLACKBOARD_SHARED)
#define NSB_BLACKBOARD_EXPORT Q_DECL_EXPORT
#else
#define NSB_BLACKBOARD_EXPORT Q_DECL_IMPORT
#endif
#endif // BLACKBOARDHEADER_H
